name: Test and Publish Mini

on:
  push:

jobs:
  test:
    name: Test and publish artifacts
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Go version
        run: go version

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y language-pack-en python-pip libffi-dev libssl-dev python-dev
          sudo pip install --upgrade pip
          sudo pip install markupsafe==1.1.1 setuptools==40.8.0 ansible==2.8.1 paramiko==1.16.0

      - name: Provision a local Mini instance
        run: ansible-playbook -i $GITHUB_WORKSPACE/provisioning/inventory $GITHUB_WORKSPACE/provisioning/local_setup.yml --connection=local --become
      
      - id: 'auth'
        if: startsWith(github.ref, 'refs/tags/')
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64 }}'

      - name: 'Set up Cloud SDK'
        if: startsWith(github.ref, 'refs/tags/')
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Extract tag from ref
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | sed "s/refs\/tags\///")

      - name: Publish artifact based on cloud and size
        if: startsWith(github.ref, 'refs/tags/')
        env:
          AWS_DEPLOY_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          AWS_DEPLOY_SECRET_KEY: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64 }}
        run: $GITHUB_WORKSPACE/.github/workflows/deploy.sh ${{ steps.get_tag.outputs.VERSION }}
